Repository daxoron/PSQ, pull requests merged in 2022-10, with the labels that each got.

#32 Created a Optimized Approach for A LeetCode Question
  Questions/Question1.cpp
Labels: #hacktoberfest-accepted, #hacktoberfest

#33 OptimizedGreedyAlgorithm CodeForces
  Questions/OptimizedGreedyAlgorithm.cpp
Labels: good first issue, hacktoberfest

#34 Time/Spaze Optimized Code For Stacks
  Questions/OptimizedGraphAlgorithm.cpp
  Questions/StackBasedOptimized.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#35 FizzBuzz
  Questions/Optimzed_Fizz_Buzz.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#36 Optimzed Codeforces Judge Sol
  Questions/Optimzed_CodeforcesSol.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#37 KickStart_OptimizedSol
  Questions/KickStart.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#38 Unordered_MapOptimized
  Contributed Codes/UMap/umap.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#40 Optimized Code For Dynamic Programming
  Contributed Codes/DynamicProgramming/DP.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#43 IsPalin Optimized Code
  Contributed Codes/1_isPalindrome.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#44 OptimizedCode CPP For BST
  Contributed Codes/main.cpp
Labels: hacktoberfest, hacktoberfest-accepted
